name: Build ATC_Thermometer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: skaldo/telink-sdk:0.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ATC_Thermometer
        run: |
          cd ATC_Thermometer
          make
          cd $GITHUB_WORKSPACE
          ls -la
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: true
      - name: upload ATC_Thermometer.bin to releases
        id: upload-atc-thermometer-binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ATC_Thermometer.bin
          asset_name: ATC_Thermometer.bin
          asset_content_type: application/octet-stream
      - name: zip output directory
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r output.zip out
      - name: upload output directory to releases
        id: upload-output-folder
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output.zip
          asset_name: output.zip
          asset_content_type: application/zip
